# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-13 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0002_auto_20170813_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='fullname'),
        ),
    ]
